apiVersion: v1
kind: Service
metadata:
  name: data-service-go
  namespace: crop-dashboard
spec:
  selector:
    app: data-service-go
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

