apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-service-python
  namespace: crop-dashboard
  labels:
    app: trend-service-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend-service-python
  template:
    metadata:
      labels:
        app: trend-service-python
    spec:
      containers:
        - name: trend-service-python
          image: 533267327324.dkr.ecr.us-east-1.amazonaws.com/trend-service-python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: "mysql.crop-dashboard.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE


